// Generated by CoffeeScript 1.9.1
var estacionamientos, express, request, router, usuario;

express = require('express');

request = require('request');

router = express.Router();

usuario = require('./routes-users')(router);


/* GET home page. */

router.get('/', function(req, res, next) {
  res.render('index');
}).get('/login', function(req, res) {
  res.render('login');
}).get('/signup', function(req, res) {
  res.render('signup');
});

module.exports = router;


/*
.get '/go', (req,res) ->
	request 'http://datos.labcd.mx/api/action/datastore_search?resource_id=4366bf30-01eb-4fa0-9f2a-c74153ec2b79&limit=5', (error,response,body) ->
		if !error and response.statusCode == 200
			res.send(body)
 */
