// Generated by CoffeeScript 1.9.1
var users;

users = require('../models/model-user');

module.exports = function(router) {
  return router.get('/user/:user', function(req, res) {
    var user;
    user = req.param('user');
    return res.render('home', {
      user: user
    });
  }).get('/api/user', function(req, res) {
    var user;
    user = req.body.username;
    return res.redirect('/user/' + user);
  }).get('/api/user/:username', function(req, res) {
    return users.findOne({
      username: req.param('username')
    }).exec(function(err, data) {
      if (err) {
        res.send(err);
      }
      return res.send(data);
    });
  }).post('/api/user', function(req, res) {
    var newUser;
    newUser = users({
      correo: req.body.correo,
      username: req.body.username,
      password: req.body.password
    });
    return newUser.save(function(err, doc, num) {
      if (err) {
        return res.send(err);
      } else {
        console.log(doc);
        return res.redirect('/user/' + req.body.username);
      }
    });
  });
};
