// Generated by CoffeeScript 1.9.1
var users;

User = require('../models/model-user');
mongoose = require('mongoose');

// create a new user called chris
module.exports = function(router) {
  /*var user = new User({
    name: 'Edwin',
    username: 'edva',
    password: 'password' 
  });
  user.save(function(err) {
    if (err) throw err;

    console.log('User saved successfully!');
  });*/
};
